### PR TITLE
Engine landing v2

### PR DESCRIPTION
**Pull request by easyrun42**
## PR-Codex overview
This PR updates various image assets, adds SVG icons, refactors TypeScript interfaces, and introduces new components for the landing page. 

### Detailed summary
- Updated various image assets in the `public/assets` directory
- Added new SVG icons for like, share, favorite, and retweet in the `public/assets/landingpage` directory
- Refactored TypeScript interfaces in `types.tsx` and `engine-frames.ts`
- Introduced new components `LandingDesktopMobileImage` and `EngineTierCard`
- Modified existing components `LandingHeroWithSideImage` and `SectionHeading`
- Updated CSS animation in `categories.module.css`

> The following files were skipped due to too many changes: `src/components/engine/create-engine-instance.tsx`, `src/components/homepage/open-source/opensource.module.css`, `src/components/landing-pages/image-section-item.tsx`, `src/components/engine/no-connected-wallet.tsx`, `src/pages/api/frame/engine.ts`, `src/components/engine/engine-list.tsx`, `public/assets/landingpage/verified.svg`, `src/components/landing-pages/splash-image.tsx`, `src/components/landing-pages/twitter-card.tsx`, `src/components/homepage/open-source/OpenSource.tsx`, `src/components/homepage/sections/PricingEngine.tsx`, `src/components/homepage/sections/HeroSection.tsx`, `src/classes/EngineFrame.ts`, `src/pages/engine.tsx`, `public/assets/product-pages/engine/lottie2.json`, `public/assets/product-pages/engine/lottie.json`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by jnsdls** [comment]
#### 📝 Changed routes:


| [**/engine**](https://thirdweb-ah4kyzo9f.thirdweb-preview.com/engine) |
|:-:|
|<a href="https://thirdweb-ah4kyzo9f.thirdweb-preview.com/engine">Screenshot of /engine</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/-tMnN_uQAOI3FCbki2nq9TwYTuM3bahj9jZHiWrPdtp0cU8YYrIzPPqiVkNLqQ4jZctu5AuAIV32UoQbAYeYZg.png">(view full size)</a> |







Commit 3c3ea380b80b2ddf942e7064288ad9756021d86d (https://thirdweb-ah4kyzo9f.thirdweb-preview.com).

**Comment by juandolealt** [comment]
@easyrun42 wanted to make some layout changes here - can you help me fix up prettier & unused props when you get a chance? 🙏

**Comment by juandolealt** [comment]
@jnsdls could i also get this pre-approved ahead of tomorrow? won't make any more big changes aside from maybe copy/image edits

should be able to get those in today either way, but just in case of any last-min stuff

**Review by jnsdls — APPROVED** [review]

**Comment by juandolealt** [comment]
fixed all vercel preview comments before deploying

**Pull request merged**
