### PR TITLE
Updates banner to learn announcement

### PR DESCRIPTION
**Pull request by mmeigooni**
And fixes a small typo

### CODE REVIEW

**Comment by jnsdls** [comment]
#### 📝 Changed routes:


| [**/learn**](https://thirdweb-py3av0zjy.thirdweb-preview.com/learn) |
|:-:|
|<a href="https://thirdweb-py3av0zjy.thirdweb-preview.com/learn">Screenshot of /learn</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/wnDRNSw3nWKsF6aTmv1YZ2EwcyPAC9Gl0Ibo-G5CetlltZibKgZXnKfFECsUN7iHynkA0XiYZKC2lCSMxLhRGw.png">(view full size)</a> |







Commit 44c097e2b7920aa497bf4f9035c7652817292b32 (https://thirdweb-py3av0zjy.thirdweb-preview.com).

**Review by jnsdls — APPROVED** [review]
LGTM, you may want to also update the gradient of the banner but that's optional

**Comment by mmeigooni** [comment]
Gradient looks 👌

Do I go ahead and merge when it's ready?

**Comment by jnsdls** [comment]
> Gradient looks 👌
> 
> Do I go ahead and merge when it's ready?

yup, ship it

**Pull request merged**
