### PR TITLE
Quick SEO fixes

### PR DESCRIPTION
**Pull request by juandolealt**

### CODE REVIEW

**Review by nachoiacovino — APPROVED** [review]

**Comment by juandolealt** [comment]
hmm, any idea why this didn't work @nachoiacovino?

**Comment by juandolealt** [comment]
thanks @jnsdls @shift4id!! lmk also if there's anything i should do moving forward to prevent this from happening when making a pr 🙏

**Comment by jnsdls** [comment]
#### 📝 Changed routes:


| [**/faucet/solana**](https://thirdweb-l8g9jxtcy.thirdweb-preview.com/faucet/solana) |
|:-:|
|<a href="https://thirdweb-l8g9jxtcy.thirdweb-preview.com/faucet/solana">Screenshot of /faucet/solana</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/o9j-OUXvdAghyMTVNQ-yFJlup0kB12aVbqh6Q0Gq4ickeTFZrNdFFw-QTzEC_ChzLKMP8O736Ki-LwV3kZK04w.png">(view full size)</a> |







Commit 492498fd4fb7767b31eab485050c0cf4ef84ac79 (https://thirdweb-l8g9jxtcy.thirdweb-preview.com).

**Comment by juandolealt** [comment]
sounds good, thanks @shift4id!!

**Pull request merged**
