### PR TITLE
Adding ambassadors page

### PR DESCRIPTION
**Pull request by SamuSarmiento**
@nachoiacovino Could you check if you can do the merge correctly now?

### CODE REVIEW

**Comment by SamuSarmiento** [comment]
Yes @nachoiacovino , I can do the same as /about, I can create an object for the ambassador card and also create const ambassadorMonth. Then I'll add all the images in the same folder, public/assets/ambassadors,.

**Comment by nachoiacovino** [comment]
> Yes @nachoiacovino , I can do the same as /about, I can create an object for the ambassador card and also create const ambassadorMonth. Then I'll add all the images in the same folder, public/assets/ambassadors,.

sound good, also I noticed a typo with Waren's name, should be only one R.

**Comment by SamuSarmiento** [comment]
> 

Create objects for ambassadors and ambassadorMonthly. The public/assets/ambassadors folder and added the corresponding images there. 

I'm Junior, you can tell right? hahaha I hope this time it's all right...!

**Comment by nachoiacovino** [comment]
hey @SamuSarmiento the build is failing, can you run `yarn build` locally and make sure it passes?

**Comment by SamuSarmiento** [comment]
Hey @nachoiacovino :

95:3  Error: Insert `␍`  prettier/prettier

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

image

**Comment by SamuSarmiento** [comment]
> Hey @nachoiacovino :
> 
> 95:3 Error: Insert `␍` prettier/prettier
> 
> info - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> image

How Can I fix this? Any Idea?

**Comment by nachoiacovino** [comment]
hey @SamuSarmiento you should insteall the Prettier extension then format the files you changed, we enforce that the build fail if the code is not formatted correctly

**Comment by SamuSarmiento** [comment]
> hey @SamuSarmiento you should insteall the Prettier extension then format the files you changed, we enforce that the build fail if the code is not formatted correctly

Prettier's problems should be fixed by now as I was able to do the yarn build with "endOfLine": "auto".

There shouldn't be any problems with the merge now, as it is now formatted correctly.

**Comment by SamuSarmiento** [comment]
@nachoiacovino Is it also possible that there are errors because I am using Windows?

**Comment by nachoiacovino** [comment]
hey @SamuSarmiento we ended up doing this a bit different and it's already live at https://thirdweb.com/ambassadors

**Pull request closed without merging**
