### PR TITLE
ClaimCondition Form: Disable snapshot edit button when form is disabled

### PR DESCRIPTION
**Pull request by MananTank**
### Current Behavior

* "See Snapshot button" is always enabled for non-admin user
* "Edit Snapshot button" is always enabled for admin user

https://user-images.githubusercontent.com/22043396/212715976-e51569f5-6253-4145-8c81-a73595af7e39.mov

### New Behavior

* "See Snapshot button" is always enabled for non-admin user
* "Edit Snapshot button" is always disabled when form data is being fetched for the admin user

https://user-images.githubusercontent.com/22043396/212717221-1baf1997-75f8-4330-89bf-702b85d93585.mov

### CODE REVIEW

**Comment by MananTank** [comment]
@nachoiacovino Please verify the updated behavior

**Review by nachoiacovino — APPROVED** [review]
I could be very nitpicky and be annoyed at the green color of "2 addresses in snapshot" being too green when everything else gets a disabled taint, but not worth it :D

functionality works great, thanks!

**Comment by MananTank** [comment]
@nachoiacovino Reduced opacity for the text as well 

disabled: 

image


enabled: 

image

**Comment by nachoiacovino** [comment]
love it!

**Pull request merged**
