### PR TITLE
fix network filter across pages on dashboard

### LINKED ISSUE #1204: Filter by Network Does Not Filter Past First Page
Introduced in #1192 

See a video here on steps to reproduce:
https://www.loom.com/share/c3df2cd252474514b35e9772bcfb9f9f

I can take on creating a PR to address it

### PR DESCRIPTION
**Pull request by mykcryptodev**
Fixes #1204

### CODE REVIEW

**Comment by MananTank** [comment]
@mykcryptodev - We wanna keep the show more button for performance reasons
I've fixed this issue in https://github.com/thirdweb-dev/dashboard/pull/1205

**Comment by mykcryptodev** [comment]
> @mykcryptodev - We wanna keep the show more button for performance reasons I've fixed this issue in #1205

@MananTank Im looking into that issue about getting double Show More buttons on #1205 but in the meantime, this PR also has a Show More button ([see line 532](https://github.com/thirdweb-dev/dashboard/blob/fe3ccf9e45f8b4b9242f52628b69144a87367aa2/components/contract-components/tables/deployed-contracts.tsx#L532))

**Comment by MananTank** [comment]
@mykcryptodev Looks like this is a better solution than https://github.com/thirdweb-dev/dashboard/pull/1205

**Comment by mykcryptodev** [comment]
@MananTank <3 ty for your help! I just pulled in the latest and put the changes back on top

**Comment by MananTank** [comment]
@mykcryptodev Thank you!

**Pull request merged**
