### PR TITLE
Update deployed + published contracts page

### PR DESCRIPTION
**Pull request by shift4id**

### CODE REVIEW

**Comment by jnsdls** [comment]
#### 📝 Changed routes:


| [**/dashboard/contracts**](https://thirdweb-mqjya8vn4.thirdweb-preview.com/dashboard/contracts) | [**/dashboard/published**](https://thirdweb-mqjya8vn4.thirdweb-preview.com/dashboard/published) |
|:-:|:-:|
|<a href="https://thirdweb-mqjya8vn4.thirdweb-preview.com/dashboard/contracts">Screenshot of /dashboard/contracts</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/uvNnVlhBqJrtikEKhrNethb4k0MY53gDLkjmRy-rJAbPEE8jyNAr2FJ9j4Wf4RaC6aCZknsHBI3doTZZHGbk2A.png">(view full size)</a> |<a href="https://thirdweb-mqjya8vn4.thirdweb-preview.com/dashboard/published">Screenshot of /dashboard/published</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/AlZGX93j14T_8_vwyzYqhNujbZkaBpDcC82VQSL71rCKHhOj19i1xCFd6IEHnTLSQ5SkI9OSYdZ-q3kf-BfI4Q.png">(view full size)</a> |







Commit dab3695d24669c7de876d42167452a253f18f9bc (https://thirdweb-mqjya8vn4.thirdweb-preview.com).

**Comment by jnsdls** [comment]
`/dashboard/contracts/published` 404

**Comment by nachoiacovino** [comment]
I think we should not show the FTUX if you already have done all the steps.

Also, we mention "or import a contract" on the FTUX but we don't explain how or give you a button to do it, would add a 4th option.

**Comment by jnsdls** [comment]
> I think we should not show the FTUX if you already have done all the steps.
> 
> Also, we mention "or import a contract" on the FTUX but we don't explain how or give you a button to do it, would add a 4th option.

product decision

**Comment by jnsdls** [comment]
@shift4id let's make the `/explore` link not open in new tab, then ship it

**Pull request merged**
