### PR TITLE
RE: #1155 - Optimize Data Fetching

### PR DESCRIPTION
**Pull request by BankkRoll**
RE: Update to include thirdweb-dev & thridwed-examples, optimize and fix from #1155

### CODE REVIEW

**Comment by jnsdls** [comment]
#### 📝 Changed routes:


| [**/open-source**](https://thirdweb-ekowlmt0s.thirdweb-preview.com/open-source) |
|:-:|
|<a href="https://thirdweb-ekowlmt0s.thirdweb-preview.com/open-source">Screenshot of /open-source</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/3RbL-GZlB-4X44G9EKbEVGEefP7_DuTBpbYc2bN_zKJPLCvYo7TOUmCbKrlk-UYr7HQz8rzBJ9kwD0UhY8So7g.png">(view full size)</a> |







Commit d65038b49aebf9d7430d029955e1f54220826e53 (https://thirdweb-ekowlmt0s.thirdweb-preview.com).

**Comment by BankkRoll** [comment]
lol idk what i did was just working in my dev server testing it... sorry dont know why it pushed differently? ill check again was working untill i switched it to the promise all 🤣

**Comment by nachoiacovino** [comment]
> 

seems like it's working fine but we need the list of profiles we're filtering out (all thirdweb internal profiles)

**Comment by BankkRoll** [comment]
> > 
> 
> seems like it's working fine but we need the list of profiles we're filtering out (all thirdweb internal profiles)

image

yeah wasnt updating on my side correctly, repo seems to make my pc freeze and load super slow sorry... pushed fixes also added bots to filter

**Comment by jnsdls** [comment]
thx @BankkRoll!

**Pull request merged**
