### PR TITLE
feature: high-level chain analytics on chain page

### PR DESCRIPTION
**Pull request by gerrysaporito**
### Spec
[Eng Spec](https://www.notion.so/thirdweb/On-Chain-Analytics-1480364f2f4e4ce2b0bd11828328319b)

### Output
image

### CODE REVIEW

**Comment by jnsdls** [comment]
#### 📝 Changed routes:


| [**/chain/\[chainSlug\]**](https://thirdweb-1nyczuxl0.thirdweb-preview.com/chain/[chainSlug]) |
|:-:|
|<a href="https://thirdweb-1nyczuxl0.thirdweb-preview.com/chain/[chainSlug]">Screenshot of /chain/[chainSlug]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/r4Cr4qyPx0VkLBoTw9D8UfRSctXmHan_dlSqTdD8IOWTk9mQIkoPgCYY3HybGXp00rvUJi0ofROhPy3pavoHNg.png">(view full size)</a> |







Commit 2c198539a568d4f12d91076105e818b6e9edb4f5 (https://thirdweb-1nyczuxl0.thirdweb-preview.com).

**Comment by jnsdls** [comment]
@gerrysaporito is this still active?

**Comment by gerrysaporito** [comment]
> @gerrysaporito is this still active?

This PR is not active right now (but will need to be revisited)

This PR was ready to go but now we need to go through a design iteration and update the metrics we want to show in a new format (TBD)

**Comment by nachoiacovino** [comment]
closing for now, we'll do it differently and with a new design

**Pull request closed without merging**
