### PR TITLE
Use new storage cutover SDK

### PR DESCRIPTION
**Pull request by nessup**

### CODE REVIEW

**Comment by jnsdls** [comment]
#### 📝 Changed routes:


| [**/dashboard/rpc**](https://thirdweb-4gzdiib9z.thirdweb-preview.com/dashboard/rpc) |
|:-:|
|<a href="https://thirdweb-4gzdiib9z.thirdweb-preview.com/dashboard/rpc">Screenshot of /dashboard/rpc</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/_05oJgmLP2uwCArAGTPPVejxS-qsr9HROqDiQhsi1FWpJ_6LPmzvdwGR0oYWR74jEFA63lA4R2AVFAGQvBaYAg.png">(view full size)</a> |







Commit 2591e9fc50e239b61cd96d345dbeac00479f9168 (https://thirdweb-4gzdiib9z.thirdweb-preview.com).

**Comment by jnsdls** [comment]
why are there so many changes to yarn.lock? that looks like someone deleted it & re-installed?

**Comment by nessup** [comment]
@jnsdls It looks like the project is being developer with yarn@1, and I was using yarn@2. I've downgraded to @1 so it's not an issue any more

**Comment by nachoiacovino** [comment]
superseded a while ago

**Pull request closed without merging**
