### PR TITLE
chore: add gradient component with connect page

### PR DESCRIPTION
**Pull request by easyrun42**
## PR-Codex overview
This PR adds gradient components and updates link button props across landing pages components.

### Detailed summary
- Added `Gradients` component with top and bottom gradient positions
- Updated link button props in multiple components
- Removed unused images and imports

> The following files were skipped due to too many changes: `public/assets/landingpage/top-gradient.svg`, `src/pages/connect.tsx`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by jnsdls** [comment]
#### 📝 Changed routes:


| [**/connect**](https://thirdweb-bf1moefrh.thirdweb-preview.com/connect) | [**/solutions/chains**](https://thirdweb-bf1moefrh.thirdweb-preview.com/solutions/chains) |
|:-:|:-:|
|<a href="https://thirdweb-bf1moefrh.thirdweb-preview.com/connect">Screenshot of /connect</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/OSAwqzpv_3yDqiHCH8XqD1KF_Ee5kjR3R3qPoDNn-PWYUCiFAaq-3v1wi9Xj4bKMgBzjGiHWhXkhSWc1cPA1kg.png">(view full size)</a> |<a href="https://thirdweb-bf1moefrh.thirdweb-preview.com/solutions/chains">Screenshot of /solutions/chains</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/7-uVcsgKsCPR4Cg3Z1ko6Wwumhh8hxdX3AG8QdHe7pKJYvfYLwlRbpbI_tIVA4583iWK274uZLKQyQQJ3H8Mug.png">(view full size)</a> |







Commit 4485168b74f50a03fea93c14c9c108700262a388 (https://thirdweb-bf1moefrh.thirdweb-preview.com).

**Comment by jnsdls** [comment]
the assets are pretty huge, any way we can shrink them down?

**Review by jnsdls — APPROVED** [review]
if we can tinypng the assets or maybe turn them into webp or _something_ to shrink them down that would be great - other than that lgtm

**Comment by juandolealt** [comment]
@jnsdls tried tinypng'ing it, turning into webp, etc but looks really bad

not having loading issues on the page with these currently in it: https://thirdweb.com/solutions/chains

can we merge & i monitor for any traffic/conversion drops?

**Comment by jnsdls** [comment]
> @jnsdls tried tinypng'ing it, turning into webp, etc but looks really bad
> 
> not having loading issues on the page with these currently in it: https://thirdweb.com/solutions/chains
> 
> can we merge & i monitor for any traffic/conversion drops?

yes, we can merge it with the larger assets - in general massive assets like this are bad however and we need to find ways to reduce / avoid them

**Comment by juandolealt** [comment]
@jnsdls yeah agree - we'll try finding ways to compress + will check with carmen. ty!

**Pull request merged**
