### PR TITLE
various improvements

### PR DESCRIPTION
**Pull request by jnsdls**

### CODE REVIEW

**Comment by jnsdls** [comment]
#### 📝 Changed routes:


| [**/contracts**](https://thirdweb-85ggy68r6-thirdweb.vercel.app/contracts) |
|:-:|
|<a href="https://thirdweb-85ggy68r6-thirdweb.vercel.app/contracts">Screenshot of /contracts</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/sl12T26UXe4BRBQjeAwizrINqVmdpVa9lek_B8zHm_h5PTIUjPvONaPJKuwcBqOoNqjhrUxupBpRjyafOXV3rA.png">(view full size)</a> |







Commit a52acfec3672a4a37b11e15770c3343445c14147 (https://thirdweb-85ggy68r6-thirdweb.vercel.app).

**Comment by nachoiacovino** [comment]
CTA is great.

Are we not making the whole row clickable and getting rid of the Details button?

Basically goal is to standarize tables with the /dashboard table and not the NFTs list table on custom contracts.

**Comment by jnsdls** [comment]
> CTA is great.
> 
> Are we not making the whole row clickable and getting rid of the Details button?
> 
> Basically goal is to standarize tables with the /dashboard table and not the NFTs list table on custom contracts.

yeah the table is just getting too complicated. I wanna kind of do that as a separate arc of work. We're currently putting distinctly different responsibilities into the same table and it's becoming too much of a hassle

**Comment by jnsdls** [comment]
_also LGTM is plain wrong_

**Comment by nachoiacovino** [comment]
> _also LGTM is plain wrong_

they might just want `!!outlineBorder`? :D

**Comment by jnsdls** [comment]
> > _also LGTM is plain wrong_
> 
> they might just want `!!outlineBorder`? :D

nah nvm they were right, I was wrong :(

**Comment by joaquim-verges** [comment]
NEVER disrespect LGTM like that again

**Comment by joaquim-verges** [comment]
CTA is much clearer - wonder if we need that gradient border... don't feel too strongly though

**Pull request merged**
