### PR TITLE
Settings feature detection

### PR DESCRIPTION
**Pull request by nachoiacovino**

### CODE REVIEW

**Comment by joaquim-verges** [comment]
@nachoiacovino my contract implements metadata + royalties but doesnt show anything - https://thirdweb-a4t80tt3o-thirdweb.vercel.app/dashboard/goerli/0xE646849d679602F2588CA8eEDf0b261B1aB085AF/settings

**Comment by joaquim-verges** [comment]
cc @jnsdls

**Comment by jnsdls** [comment]
will take a look

**Comment by joaquim-verges** [comment]
@nachoiacovino @jnsdls ship iiiit

**Pull request merged**
